### ISSUE TITLE
启动报错（跳过有问题的元数据日志，不影响重启）

### ISSUE THREAD

**Issue by china-bigcloud** [apache/incubator-iotdb#1238]
[root@localhost sbin]# ./start-server.sh &
[1] 10397
[root@localhost sbin]# ---------------------
Starting IoTDB
---------------------
Maximum memory allocation pool = 4096MB, initial memory allocation pool = 800MB
If you want to change this configuration, please check conf/iotdb-env.sh(Unix or OS X, if you use Windows, check conf/iotdb-env.bat).
2020-05-22 18:43:19,086 [main] INFO  org.apache.iotdb.db.conf.IoTDBDescriptor:91 - Start to read config file ./../conf/iotdb-engine.properties 
2020-05-22 18:43:19,089 [main] INFO  org.apache.iotdb.db.conf.IoTDBDescriptor:111 - The stat_monitor_detect_freq_sec value is smaller than default, use default value 
2020-05-22 18:43:19,090 [main] INFO  org.apache.iotdb.db.conf.IoTDBDescriptor:118 - The stat_monitor_retain_interval_sec value is smaller than default, use default value 
2020-05-22 18:43:19,090 [main] INFO  org.apache.iotdb.db.conf.IoTDBDescriptor:228 - Time zone has been set to +08:00 
2020-05-22 18:43:19,093 [main] INFO  org.apache.iotdb.tsfile.common.conf.TSFileDescriptor:103 - Start to read config file ./../conf/iotdb-engine.properties 
2020-05-22 18:43:19,095 [main] INFO  org.apache.iotdb.db.conf.IoTDBConfigCheck:54 - System configuration is ok. 
2020-05-22 18:43:19,097 [main] INFO  org.apache.iotdb.db.service.StartupChecks:47 - JMX is enabled to receive remote connection on port 31999 
2020-05-22 18:43:19,097 [main] INFO  org.apache.iotdb.db.service.StartupChecks:57 - JDK veriosn is 8. 
2020-05-22 18:43:19,098 [main] INFO  org.apache.iotdb.db.service.IoTDB:80 - Setting up IoTDB... 
2020-05-22 18:43:19,111 [main] ERROR org.apache.iotdb.db.concurrent.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread main-1 
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.iotdb.db.metadata.MManager.operation(MManager.java:217)
	at org.apache.iotdb.db.metadata.MManager.initFromLog(MManager.java:177)
	at org.apache.iotdb.db.metadata.MManager.init(MManager.java:149)
	at org.apache.iotdb.db.service.IoTDB.initMManager(IoTDB.java:121)
	at org.apache.iotdb.db.service.IoTDB.setUp(IoTDB.java:92)
	at org.apache.iotdb.db.service.IoTDB.active(IoTDB.java:69)
	at org.apache.iotdb.db.service.IoTDB.main(IoTDB.java:55)
2020-05-22 18:43:19,114 [Thread-1] INFO  org.apache.iotdb.db.service.IoTDBShutdownHook:32 - IoTDB exits. Jvm memory usage: 0 GB 40 MB 104 KB 256 B 

我这里主要存zabbix监控信息，使用了一个存储组，每1分钟存2000条时序数据，我应该调整哪些内存参数？我现在使用1台4核16G机器。

我修改了iotdb-env.sh中的配置：
    half_system_memory_in_mb=`expr $system_memory_in_mb / 2`
    quarter_system_memory_in_mb=`expr $half_system_memory_in_mb / 2`
    if [ "$half_system_memory_in_mb" -gt "1024" ]
    then
        half_system_memory_in_mb="4096"
    fi
    if [ "$quarter_system_memory_in_mb" -gt "8192" ]
    then
        quarter_system_memory_in_mb="8192"
    fi
    if [ "$half_system_memory_in_mb" -gt "$quarter_system_memory_in_mb" ]
    then
        max_heap_size_in_mb="$half_system_memory_in_mb"
    else
        max_heap_size_in_mb="$quarter_system_memory_in_mb"
    fi
    MAX_HEAP_SIZE="${max_heap_size_in_mb}M"

    # Young gen: min(max_sensible_per_modern_cpu_core * num_cores, 1/4 * heap size)
    max_sensible_yg_per_core_in_mb="200"
    max_sensible_yg_in_mb=`expr $max_sensible_yg_per_core_in_mb "*" $system_cpu_cores`

    desired_yg_in_mb=`expr $max_heap_size_in_mb / 4`

    if [ "$desired_yg_in_mb" -gt "$max_sensible_yg_in_mb" ]
    then
        HEAP_NEWSIZE="${max_sensible_yg_in_mb}M"
    else
        HEAP_NEWSIZE="${desired_yg_in_mb}M"
    fi

请问这个问题如何解决？

**Comment by HTHou** [comment]
您好，请问您在使用哪个版本的IoTDB？

**Comment by qiaojialin** [comment]
应该是做了错误的元数据操作，0.9.3 版本修复了这个启动问题，可以升级到 0.9.3

**Comment by china-bigcloud** [comment]
我正在使用的是0.9.3

**Comment by china-bigcloud** [comment]
另外，我不太明白我该如何调整内存配置，首先我使用一个存储组，这个存储组下有10几个子节点，每个节点TTL是30天，那么每个节点就有43200条记录，10个节点就是43万条顺序的记录，当我使用./memory-tool.sh calmem -sg 1 -ts 432000计算内存时，得到Memory for writing: 14GB，那么我需要如何修改itodb-env.sh以适应这个数据量级？

**Comment by qiaojialin** [comment]
您好，加个微信  qiaojialin1993

**Comment by jixuan1989** [comment]
@qiaojialin 问题解决后请来这里反馈下原因和解决方法

**Comment by qiaojialin** [comment]
路径最后一层存在特殊字符，比如 [/.s1]，而且没用双引号括起来，启动时候跳过了这些错误的日志，没有影响服务器启动。

路径最后一层如果想有多个 . 和特殊字符，可以用双引号括起来，不过所有insert、select查询都需要把最后一层括起来，下面这种是可以的：

create timeseries root.host_item_test."vfs.fs.size[/,free]" with datatype=FLOAT, encoding=RLE, compression=SNAPPY
insert into root.host_item_test(timestamp,"vfs.fs.size[/,free]") values(1,1)
select "vfs.fs.size[/,free]" from root.host_item_test

**Comment by qiaojialin** [comment]
另外，./memory-tool.sh calmem -sg 1 -ts 432000，这个 -ts 指的是时间序列数量，432000是实际的数据点个数，不是一个维度的。几万时间序列的负载一般都不需要计算这个内存，系统内部会自动调整
